id: op:P000780
initial_creation_type: input
source_metadata:
  source_src:     # resource in initial release
  source_bdr:     # BDRC Resource ID
  source_url: https://bo.wikipedia.org/wiki/%E0%BD%96%E0%BE%B3%E0%BD%BC%E0%BC%8B%E0%BD%A6%E0%BE%A6%E0%BE%B1%E0%BD%BC%E0%BD%84%E0%BC%8B%E0%BD%9A%E0%BD%B2%E0%BD%82%E0%BC%8B%E0%BD%A2%E0%BE%90%E0%BD%84%E0%BC%8B%E0%BD%96%E0%BD%A2%E0%BE%92%E0%BE%B1%E0%BD%91%E0%BC%8B%E0%BD%98%E0%BC%8B      # other
  title: བློ་སྦྱོང་ཚིག་རྐང་བརྒྱད་མ།
  author: 'གླང་རི་ཐང་པ།'
